### ISSUE TITLE
Sticky Pistons Bugged

### ISSUE THREAD

**Issue by NotoriousV2** [marcelo-mason/PreciousStones#896] opened 2015-11-08 23:31 UTC
Hey. There's another issue open for this but the way it is worded really doesn't make much sense.

Sticky pistons are currently bugged. Players are able to place a sticky piston outside of a protected field (one with a no-destroy flag), activate it, and pull the block out of the protected field. Same issue with the protection stone itself, but I assume it's caused by the same bug.

Could this bug be fixed? It's quite game-breaking on our server unfortunately.

**Comment by JordiAB** [comment] 2015-11-19 00:52
You can use the plugin PistonOre to make you want protective stones are not moved by the pistons.
And it works on any cube, I'm disabling the enderstone and sponge.
https://www.spigotmc.org/resources/pistonore.10529/

**Comment by marcelo-mason** [comment] 2015-11-22 02:23
Fixed on latest dev build, duplicate of #900

**Closed by marcelo-mason** 2015-11-22 02:23 UTC
