### ISSUE TITLE
Sticky Piston BUG

### ISSUE THREAD

**Issue by JordiAB** [marcelo-mason/PreciousStones#891] opened 2015-10-25 15:53 UTC
The sticky pistons do to stay protected site and get free protection. When you sprucing it?

If you put a sticky piston prune and move the precious stone will continue to catch and place protected.

**Comment by marcelo-mason** [comment] 2015-11-22 02:23
Fixed on latest dev build, duplicate of #900

**Closed by marcelo-mason** 2015-11-22 02:23 UTC
